---

- name: Install MySQL packages
  action: >
    {{ ansible_pkg_mgr }} name={{ mysql_package_list }} state=present update_cache=yes
  notify:
    - Initialize mysql instance
    - Required mysql directories exist
    - Standalone instance configuration files
    - Alternate instance configuration files
    - Start mysql service

- name: Flush handlers
  meta: flush_handlers

- name: Install pip packages
  pip:
    name: "{{ pip_packages }}"
    executable: pip3
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"

- name: Check node is accepting mysql connections
  wait_for:
    host: "localhost"
    port: "3306"
    delay: 5
    timeout: 180
    state: started
    msg: "Node is now accepting mysql connections"
  connection: local
  when: galera_cluster_settings.enabled | bool
