---

- name: Create /etc/sysctl.d directory
  file:
    path: "/etc/sysctl.d"
    state: directory
    mode: '0755'
  when: ansible_distribution == 'Fedora'

- name: OS configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    force: yes
  loop: "{{ config_templates }}"
  register: config_files
  notify:
    - Reload sysctl

- name: Flush handlers
  meta: flush_handlers

- name: Increase max open files for system/users
  lineinfile:
    path: "{{ item.name }}"
    regexp: "DefaultLimitNOFILE"
    line: DefaultLimitNOFILE=256000:1000000
    state: present
  loop:
    - { name: "/etc/systemd/system.conf" }
    - { name: "/etc/systemd/user.conf" }

- name: Mount with noatime in /etc/fstab
  replace:
    backup: yes
    path: /etc/fstab
    regexp: '^(\S+)(\s+)(\S+)(\s+)(ext4|xfs)(\s+)(((?!noatime)\S)*)(\s+)(\d)(\s+)(\d)$'
    replace: '\1\2\3\4\5\6\7,noatime\9\10\11\12'
  when: not ansible_virtualization_type | regex_search("docker|container")
