---

- name: Create client configuration file
  template:
    src: "mysql/client/mysql-client.cnf.j2"
    dest: "{{ ansible_user_dir }}/.my.cnf"
    mode: 0600
  when: ansible_os_family == 'RedHat' and (mysql_install_settings.root_password is defined and mysql_install_settings.root_password|length > 0)

- name: set python version
  set_fact:
    ansible_python_interpreter: "/usr/bin/python3"
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Remove anonymous users
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_conf_settings.socket }}"
    login_db: mysql
    query:
      - DELETE FROM mysql.user WHERE User=''

- name: Disallow remote root login
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_conf_settings.socket }}"
    login_db: mysql
    query:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')

- name: Remove test database
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_conf_settings.socket }}"
    login_db: mysql
    query:
      - DROP DATABASE IF EXISTS test
      - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Set Root password
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysql_conf_settings.socket }}"
    login_db: mysql
    query:
      - ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_install_settings.root_password }}'; FLUSH PRIVILEGES;
  when: mysql_install_settings.root_password is defined and mysql_install_settings.root_password|length > 0

- name: Change MySQL port to {{ mysql_conf_settings.port }}
  seport:
    ports: "{{ mysql_conf_settings.port }}"
    proto: tcp
    setype: mysqld_port_t
    state: present
  when: ansible_os_family == 'RedHat' and (mysql_conf_settings.port|int != 3306 and ansible_selinux.status == 'enabled')
