---

- name: Converge
  hosts: all
  vars:
    mysql_install_settings:
      use_mariadb: true
      version: 10.6
      root_password: ''

    galera_cluster_settings:
      enabled: false
      wsrep_sst_method: "mariabackup"
      wsrep_sst_user: "cluster_sstuser"
      wsrep_sst_pass: "2rZXRAwl28Vy"
      wsrep_provider_options: "gcache.recover=yes; gcache.size=128M; gcache.page_size=128M"
      wsrep_cluster_name: "GaleraCluster"

  tasks:

    - name: "Include hybridadmin.mysql"
      include_role:
        name: "hybridadmin.mysql"
